# Python Básico para Computação Numérica

## André Luiz da Costa Carvalho
### andre@icomp.ufam.edu.br


## Na Aula de Hoje:

-  Python básico
-  Básico do use de Notebooks Jupyter
-  Vetores em Numpy
-  Plotando com Matplotlib


## Introdução

Nesta aula, veremos algumas formas de utilizar Python para computação numérica. Se você já conhece Python, ótimo. Esta aula não focará na linguagem básica. Se não conhece, tudo bem. Para o que veremos nesta aula, basta um conhecimento bem básico.

Pré-Requisitos de Software: Python 3.X + Numpy + Matplotlib + Jupyter.

#### Como instalar?

Jeito mais simples: baixe o Anaconda, que já instalará todos os pacotes necessários https://www.anaconda.com/download/

Se quiser, pode ir instalando tudo manualmente também (se vire)

#### Para rodar o Jupyter notebook

__No lab:__ Vá a um terminal e rode: `jupyter notebook`

__Com o Anaconda:__ abra um prompt anaconda e lá rode o mesmo comando (ou escolha no menu)


## Python Básico com Notebooks

_Tenha certeza que você rodou o jupyter notebook e que usou ele pra rodar o arquivo aulaPython.ipynb_


Um notebook python é uma forma simplificada de misturar texto e código Python, simplificando a documentação e explicação de seu funcionamento. A unidade básica em um notebook é a célula.

#### Rode a célula abaixo selecionando-a e pressionando Shift+enter:

Linguagem markdown que é essa forma de escrever os textos nas células

Markdown são células de texto

Jupyter roda o python iterativo no fundo
é como se tivesse usado o comando python3 no terminal

In [1]:
4*2

8

Aperte 'a' para criar uma célula acima da atual, e 'b' abaixo. Você também pode usar os menus para isto. Para transformar uma célula em texto (markdown), aperte m. Para transformar em código de novo, aperte y. Ctrl+Shift+- Quebra a célula em duas.

## Kernels

As células de código são interpretadas pelo Python. Após uma célula ser rodada, um número aparece entre os colchetes. Este número indica __a ordem__ em que as células foram executadas.

## Python Básico

Python é uma linguagem de programação com variáveis com tipos definidos, porém determinados _implicitamente_. Isto significa que o Python infere o tipo de uma variável de acordo com o contexto do seu primeiro uso. Você só vai ver erros de variável em Python se tentar fazer condições com variáveis não previamente criadas.

variavel definida implicitamente - o tipo nao é especificado
o python já vê o tipo pelo dado atribuido
as var criadas em uma célula estão disponívis em todas as células
Se reiniciar o kernel, tudo o que rodou até agora é perdido

In [2]:
n = 2+3
fl = 2.0 + 3.0
st = "string"
l = [n,fl,st]
print(n,fl,st)
print(l[0])
l

5 5.0 string
5


[5, 5.0, 'string']

Além disto, Python também aceita formatos mais "estranhos" de atribuição

In [3]:
x,y,a = 1,2,-3 # atribui na ordem
x,y = y,x # troca os valores sem uma var auxiliar
b = c = 123 # ambos recebem o mesmo valor
a+=n # n veio da celula anterior

Cada notebook tem um ambiente que guarda os valores das variáveis criadas até então, que existirão enquanto o kernel não for parado.

Cada célula, ao ser executada, mostra o conteúdos dos prints imediatamente abaixo da mesma. Se você modificar e rodar de novo, a saída anterior é apagada e a nova é mostrada.

#### Exercício

Dadas as variaveis a,b e c criadas anteriormente, assuma que são os coeficientes de uma equação de segundo grau e calcule o seu delta na célula abaixo

In [4]:
d = b**2 - 4*a*c
d

14145

### Estruturas de bloco

Em Python, os blocos são indicados unicamente atráves de __identação__. Nada de {}s nem nada. Por isso a identação em códigos Python é essencial (se estiver errada o interpretador vai dar erro). No final de cada comando que pode gerar um bloco, o operador `:` é colocado para indicar que vai começar um novo nível de identação 

#### Exemplos:

In [5]:
if x < 5 or (x > 10 and x < 20):
    print("O Valor esta OK.")

if x < 5 or 10 < x < 20:
    print("O Valor esta OK.")

# for each: iterador de listas
for i in [1,2,3,4,5]:
    print("Iteracao n#", i)

x = 10
while x >= 0:
    print("x ainda nao eh negativo.",end='\r')
    x = x-1

O Valor esta OK.
O Valor esta OK.
Iteracao n# 1
Iteracao n# 2
Iteracao n# 3
Iteracao n# 4
Iteracao n# 5


### Exercício

Adicione os valores de a,b e c abaixo e verifique quantas raízes reais uma equação de segundo grau com eles tem.

In [6]:
a = 1
b = 4
c = 1

#Checa se estes valores geram duas, uma ou nenhuma raiz real
if (a == 0):
    print("Não é uma raíz de segundo grau.")
else:
    d = b**2 - 4*a*c
    if (d > 0):
        print("Duas raízes.")
    elif (d == 0):
        print("Uma raíz.")
    else:
        print("Não possui raízes reais.")

Duas raízes.


In [7]:
for i in range(3):
    print("Valor é",i)
    
for x in range(1,5):
    print("Outro Intervalo",x)

#Decrescente com passo -2
# range(inicio,parada,passo)
for j in range(10,1,-2):
    print("Decrescente:",j)

Valor é 0
Valor é 1
Valor é 2
Outro Intervalo 1
Outro Intervalo 2
Outro Intervalo 3
Outro Intervalo 4
Decrescente: 10
Decrescente: 8
Decrescente: 6
Decrescente: 4
Decrescente: 2


Altere o código abaixo para arredondar os valores da lista abaixo para o valor inteiro mais próximo.

In [12]:
lista = [1.6,1.3,2.7,4.8,1.3,0.9]
for i in range(len(lista)):
    if (lista[i]%1 <= 0.5):
        lista[i] = int(lista[i])
    else:
        lista[i] = int(lista[i]) + 1
lista
#arredonda aqui cara

[2, 1, 3, 5, 1, 1]

O comando `for` em Python tem uma sintaxe um pouco diferente. Um `for` itera _sobre os elementos de uma lista_. A cada iteração, a variável de controle (o `i`, por exemplo) recebe um dos elementos da lista. Para fazer um for com contadores, pode-se usar a função `range()`, que cria uma lista com elementos em um intervalo dado.

### Estruturas de dados

A estrutura de dados composta mais básica no Python é a lista. Ela funciona como um vetor padrão, porém com muito mais flexibilidade. Cada elemento pode ter um tipo diferente, int, float, string ou até outras listas, e podem ser acessados via `[]`

listas em python são mais lentas que vetores em C
como as listas podem ser de qualquer tipo, não dá para fazer como C que é só sizeof(dado)*indice
é bom pq é muito maleável, mas é mais lenta fazendo malloc no meio e tudo muito louco


In [13]:
l1 = [1,2,3]
print(l1[2])
l2 = [1, 2.0, "string",[4,5,l]] #valor de l vem la de cima

print(l2)
print(l2[3][2][1])
print(len(l2),len(l2[3]))
print(2 in l1) #verifica se o elemento pertence a lista

3
[1, 2.0, 'string', [4, 5, [5, 5.0, 'string']]]
5.0
4 3
True


O acesso também pode ser feito com o operador de intervalos `:`

In [14]:
nums = list(range(1,100,2))
print(nums)
print(nums[10:20])
print(nums[-3:]) # do antepenultimo até o fim
# -1 é o último, -2 é o penúltimo...

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
[21, 23, 25, 27, 29, 31, 33, 35, 37, 39]
[95, 97, 99]


Outra estrutura impotante em Python são os dicionários: Eles são _hashs_, estruturas que associam uma chave a um conteúdo. Na prática, eles são como listas, contudo ao invés de serem indexados por números, cada elemento tem uma chave, ou nome, que é usada para identificar cada elemento. Dicionários são identificados, na criação, pelo uso de `{}` (o acesso ainda é feito por colchetes.

In [15]:
telefones = {"Jose":12345678,"Maria":66666666,"Carlos":9876543}
print(telefones["Carlos"])
pessoa = {'Nome':"Andre","Sobrenome":"Luiz",'Telefone Comercial':2345678}
print(pessoa['Nome'],pessoa['Sobrenome']+":",pessoa['Telefone Comercial'])

9876543
Andre Luiz: 2345678


Para adicionar novos campos ao dicionário, basta fazer novas atribuições. Para verificar se um valor existe, use o operador `in`

In [16]:
pessoa['Profissao']="Professor Universitario"
if("Joao" not in telefones):
    print("Sem João")

Sem João


### Funções

Funções e procedimentos em Python são feitos através da palavra reservada `def`. Parametros ficam entre parêntesis separados por vírgulas, __sem precisar do tipo__. Funções podem ter um retorno, que funciona como no C `return <valor>`. Contudo, lembre: __Tudo que está no menor nível de identação é considerado como parte da main__

In [17]:
def quadrado(x):
    return x**2

def delta(a,b,c):
    return b**2-4*a*c

def raizseg(a,b,c):
    return ((-b + delta(a,b,c)**(1/2))/2*a,(-b - delta(a,b,c)**(1/2))/2*a)


Esta última função é estranha né? Ela retorna uma tupla, no caso uma dupla. E como acessar isto?

In [18]:
r = raizseg(1,-5,6)
(x1,x2) = raizseg(1,-5,6)
print(r)
print(x1)
print(x2)

(3.0, 2.0)
3.0
2.0


### Exercícios

1 - Faça uma função norm1 que receba uma lista de valores e os normalize dividindo pelo maior da lista

2 - Faça uma função norm2 que receba uma lista de valores e os normalize dividindo pela média da lista

In [19]:
def norm1(lista):
    m = max(lista)
    for i in range(len(lista)):
        lista[i] /= m
    return lista

def norm2(lista):
    m = sum(lista)/len(lista)
    for i in range(len(lista)):
        lista[i] /= m
    return lista

In [20]:
norm1([1,2,3,4])

[0.25, 0.5, 0.75, 1.0]

In [21]:
norm2([1,2,3,4])

[0.4, 0.8, 1.2, 1.6]

### Compreensões em listas

Para terminar o básico, uma parte mais interessante: Compreensão de listas. Compreensões (_Comprehentions_) são listas criadas a partir de uma regra.

Por exemplo: Você tem uma lista e você quer gerar uma nova que contenha apenas os elementos positivos, você pode:

usa notacao de conjuntos
a = {e | e pertence L1 ^ e >= 0}
faz dicionários também
serve para aumentar a e velocidade de programação

In [24]:
l1 = [1,-2,-3,4,-5,6,-7,8]

l2 = [e for e in l1 if e>=0]
l2

[1, 4, 6, 8]

Ou se você quiser os elementos pares de uma lista sejam elevados ao quadrado:

In [25]:
l3 = [x**2 for x in l2 if x%2==0]
print(l3)


def cubo(x):
    return x**3
n = 5
dx = 1.0/(n-1)
xlist = [i*dx for i in range(n)]
ylist = [cubo(x) for x in xlist]
print(xlist,ylist)

[16, 36, 64]
[0.0, 0.25, 0.5, 0.75, 1.0] [0.0, 0.015625, 0.125, 0.421875, 1.0]


## Numpy

Para usar bibliotecas em Python, você deve usar o comando `import`. Para usar a numpy, basta fazer:

numpy = numerical python

from numpy import *
importa tudo sem precisar de np.
mas como algumas funções tem o mesmo nome de funcoes do python, bagunça
sendo que np é melho pq é mais rápido

fortran - formula translator (1960)
fazia coisas matemáticas com implementações MUITO rápidas
até outro dia, era o melhor de todos em C

cobol é aintigona e ainda usada pq ainda funciona muito bem

In [26]:
#! serve para rodar um comando do terminal
#!pip3.6 install numpy --user
import numpy as np

 Se você usar apenas `import numpy`, você vai ter que usar o nome da biblioteca antes de todas as funções (tipo `numpy.linspace()`. O `as` gera um apelido pra classe, simplificando.
 
 Numpy é a biblioteca básica de computação numérica do Python. Ela disponibiliza objetos para vetores/matrizes/tensores, bem como funções otimizadas para eles (similar ao que o MATLAB faz).
 
 ### Arrays
 
 Arrays são os arranjos padrão de Python. Podem ser vetores (1d), Matrizes (2d) ou Tensores (3+d), e são indexados por tuplas de inteiros não negativos (negativos acessam o array do fim para o início.
 
 Qual a diferença para as listas? Arrays tem um único tipo, e são __extremamente__ melhor otimizados.
 
 Usando arrays de numpy:

array é um arranjo, não vetor - ele independe o numero de dimensoes
pode ter n dimensoes:
1D - vetor
2D - Matriz
3D+ - Tensor

sao muito mais otimizados que os vetores de C

In [27]:
import numpy as np

# Cria um arranjo a partir de um vetor
a = np.array([1, 2, 3]) 
print(type(a))           
# retorna tupla com as dimensoes do arranjo
# 3 elementos na primeira dimensao e 0 na outra - é um vetor coluna: tem 3 linhas
# (colunas,linhas)
# o len dá o número de lihas
print(a.shape) 
print(a[0], a[1], a[2])   
a[0] = 5                  
print(a)                  

b = np.array([ [1,2,3],[4,5,6] ])    
print(b.shape)                     # E este?
print(b[0][0], b[0, 1], b[1, 0])   

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Usos do np.array():
converte parâmetro em arranjo

In [28]:
#array de 1 so elemento
a = np.array(1)
print(a)

array(1)

In [29]:
#transforma lista em aranjo d numpy
a = np.array([1, 2, 3])   
print(a)

[1 2 3]


In [31]:
b = np.array([ [1,2,3],[4,5,6] ])   
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [32]:
# matriz não precisa ser padrao, olha:
# Se tentar acessar o elemento [2,2], vai dar erro
# o primeiro parametro diz a dimensao em geral
b = np.array([ [1,2,3],[4,5] ])   
print(b)
print(b.shape)

[list([1, 2, 3]) list([4, 5])]
(2,)


estamos usando `np` no lugar de numpy devido ao comando `as`. Além disto, o numpy dá acesso um monte de funções para a criação de matrizes padrão:

In [33]:
#Matriz toda zerada com o shape passado por parâmetro
# se botar só um número n, nao tupla, aí vai ser um vetor de tamanho n
a = np.zeros((2,2))   
print("A:")
print(a)              

#Matriz tpreenchida com 1s com o shape passado por parâmetro
b = np.ones((1,2))   
print("B:")
print(b)              

#Matriz tpreenchida com segundo parametro com o shape passado por parâmetro
c = np.full((2,2), 7)  
print("C:") 
print(c)                         

# Matriz identidade com dimensão passada por parametro (é uma quadrada)
d = np.eye(4)         
print("D:")
print(d)              
                      
# Cria uma matriz preenchida por valores aleatórios com o shape passado por parametro
# np.random é um pack de geração de número aleatórios
e = np.random.random((2,2))  
print("E:")
print(e)                     
               
# no intervalo [0,1], gera 6 pontos linearmente espaçados
# o 0 e o 1 fazem parte tb, então se quer n pontos, passa n+1 como parametro
f = np.linspace(0,1,6)
print("F:")
print(f)
         
# é um aray gerado por um for de 1 a 99 com passo 2
# o parametro é o passo, nao o numero de pontos
i = np.arange(1,100,2)
print("I:")
print(i)

A:
[[0. 0.]
 [0. 0.]]
B:
[[1. 1.]]
C:
[[7 7]
 [7 7]]
D:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
E:
[[0.10399312 0.4354711 ]
 [0.90754863 0.2685093 ]]
F:
[0.  0.2 0.4 0.6 0.8 1. ]
I:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


Assim como com as listas, podemos acessar os arrays de numpy de forma poderosa usando o operador `:`

In [37]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1, :]   
# no caso, o : é um inter valo abert 1:3 = [1,3) = [1,2]
row_r2 = a[1:3, :] 
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  # Qual a diferenca entre row_r1 e row_r2

# Fica mais fácil de ver com colunas
# ele já inverte e tranforma em um vetor normal as colunas para não ficar estranho e precisar transpor
col_r1 = a[:, 1]
# assim gera um vetor coluna de verdade
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [39]:
# troca a ordem das linhas da matriz
# passa o índice de cada uma para dizer a ordem que quer
a[(2,0,1),:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

Além disso, você pode usar também indexação booleana para escolher elementos

In [40]:
# pega todos os elementos de a que satisfazem a condição passada
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

Operações em Numpy são lindas: Basta fazer as operações que você está acostumado (quase):

In [41]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)


print(x + y)
print(np.add(x, y)) # Sao Equivalentes

print(x - y)

# multiplica elemento por elemento com índices iguais
print(x * y) # PRODUTO ESCALAR

print(x / y)

print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Como dá para ver no comentário, `*` é o produto escalar, ao invés de multiplicação matricial. Para multiplicar duas matrizes, você deve usar a função `dot()`, que pode ser usada de duas formas, `numpy.dot(m1,m1)` ou `m1.dot(m2)`:

In [42]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

#Produto interno
print(v.dot(w))
print(np.dot(v, w))

#Matriz x vetor
print(x.dot(v))
print(np.dot(x, v))

#Matriz x Matriz
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Além disto, numpy dá diversas funções úteis sobre seus arrays:

In [43]:
print(x.sum())
print(v.mean())
print(y.min())
print(y.max())
print(y.T) # transposta

10
9.5
5
8
[[5 7]
 [6 8]]


### Exercícios

1 - Faça uma função norm1 que receba um arranjo numpy e o normalize dividindo pelo maior da lista

2 - Faça uma função norm2 que receba uma arranjo numpy e os normalize dividindo pela média da lista

In [44]:
def norm1(m):
    #todos os elementos sao uma porcentagem do maior e ficam entre 0 e 1
    # bom se o maior nao for muito grande
    return m/m.max()

def norm2(m):
    # ruim se o desvio padrão for muito alto
    return m/m.mean()

print(norm1(x))
print(norm2(x))
    

[[0.25 0.5 ]
 [0.75 1.  ]]
[[0.4 0.8]
 [1.2 1.6]]


### Por que usar Numpy?

A maioria das funções de Numpy pode ser feita sobre listas, com menos complicações.... Então por que usar Numpy?

__VETORIZAÇÃO__

Numpy utiliza de diversas operações otimizadas, que funcionam sobre grandes pedaços de vetores/matrizes ao invés de ser elemento por elemento. Ou seja, apesar da lógica ser a mesma, numpy faz operações de lote com vários elementos ao mesmo tempo, acelerando o processamento.

Por isto é importante se manter utilizando numpy quando for trabalhar com arranjos (multiplicar um arranjo por uma lista, por exemplo, não é vetorizável)

Então mesmo quando for utilizar funções simples como log ou seno, é melhor utilizar as versões de numpy para manter a vetorização:

tem otimizações ótimas que aceleram muito
mas em geral, python é mais lento pq faz muita coisa que está escondida de nós
a vetorização implementa o que quer de um jeito MUITO rápido

NUNCA processar uma matriz coluna por coluna
por linhas, é mais que o dobro o tempo
pq ao pegar um elemento, a mem carrega mais elementos da linha pra cache para tornar mais veloz
acesso a elementos de matriz: 2*i + j

gcc -O[1...15] otimiza o seu cod em C
a partir de O2 pode mudar muito sua lógica as mudanças que ele vai fazer

In [45]:
# Funções matemáticas também é melhor usar as do np
# np.sqrt() =/ sqrt()
# no e python
a = np.linspace(0,0.5,10)
a = np.sin(a*np.pi)
a

array([0.        , 0.17364818, 0.34202014, 0.5       , 0.64278761,
       0.76604444, 0.8660254 , 0.93969262, 0.98480775, 1.        ])

Funções também podem ser vetorizáveis, ou seja, rodar tanto pra escalares quanto para vetores de forma otimizada. Contudo, isto só serve para funções sem blocos condicionais ou repetições de saída.

### Pedindo Ajuda

Muitas vezes em Python, seja em notebooks ou em modo iterativo, você pode ficar com muita dúvida sobre como as coisas funcionam. Nestas horas, geralmente o rapaz corre pro google/stackoverflow. Contudo, o Python tem funções de Help embutidas:

In [46]:
# Acessa a documentação das coisas do np
help(np.sqrt)
#np. <aperte tab depois do np>
# mostra as opções

Help on ufunc object:

sqrt = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array 