# Laboratório de Raizes de Equações

Nesta aula, iremos implementar métodos para encontrar raízes de equações, polinomiais ou não.

Antes de mais nada, precisamos criar métodos para resolver um polinomio dado um valor de X. Um polinômio pode ser representado como um vetor de coeficientes. Por exemplo, um polinômio $3x^4-6x^3+4x^2-29$ poderia ser representado por:

In [1]:
import numpy as np
pol = np.array([-29,0,4,-6,3])

De posse de um polinômio, é importante ter uma função que calcule o valor do polinômio para um valor de X qualquer:

In [2]:
def resolve(coef,x):
    y = 0
    for i in range(len(coef)):
        y += coef[i]*(x**(i)) 
    return y 

In [3]:
print(resolve(pol,1.5))
print(resolve([10,-4,1],4))

-25.0625
10


Outra coisa importante pode ser uma função para calcular a derivada de um polinômio (isto pode ser útil para calcular a multiplicidade de uma raiz:

In [5]:
def deriva(coef):
    d = np.zeros(len(coef)-1)
    for i in range(1,len(coef)):
        d[i-1] = coef[i]*i
    return d

def multiplicidade(coef,raiz):
    mul=0
    d = coef
    while resolve(d,raiz) == 0 and len(d) > 0:
        mul+=1
        d = deriva(d)
    return mul

In [6]:
deriva(pol)

array([  0.,   8., -18.,  12.])

Teste seu código com a multiplicidade da raiz 1 no seguinte polinômio: $x^4+2x^3-12x^2+14x-5$:

In [7]:
multiplicidade([-5,14,-12,2,1],1)

3

Outro fator importante para encontrar as raízes de uma equação algébrica é o uso do teorema de Lagrange para encontrar os limites das raízes positivas e das negativas. Faça uma função que calcule o valor de Lagrange para um polinômio e outra que, dada os coeficientes de uma equação algébrica, retorne os quatro limites:

In [93]:
def Lagrange(coef):
    menor = 0
    if coef[-1]<0:
        coef = -coef
    for i in range(len(coef)-1,0,-1):
        if coef[i] < 0:
            menor = i
            break
    return 1+(pow(-min(coef)/coef[len(coef)-1],1/((len(coef)-1)-menor)))

def LimitesAlgebricos(coef):
    limiteSupPos = Lagrange(coef)
    limiteInfPos = 1/Lagrange(np.flip(coef,axis=0))
    aux = coef.copy()
    for i in range(1,len(aux),2):
        aux[i] = -aux[i]
    limiteSupNeg = -Lagrange(aux)
    limiteInfNeg = -1/Lagrange(np.flip(aux,axis=0))
    return (limiteSupPos,limiteInfPos,limiteSupNeg,limiteInfNeg)


Verifique o funcionamento das suas funções criadas para o polinomio: $-x^4-2x^3+12x^2-14x+5$

In [94]:
p = np.array([5,-14,12,-2,-1])
Lagrange(p)

4.464101615137754

Outro fator importante é a regra de sinal de descartes. Faça uma função que retorne o número de raízes positivas e negativas (se não puder precisar o número de negativas, retorne -1):

In [96]:
def nraizes(coef):
    npositivas = 0
    nnegativas = 0
    aux = np.array([])
    for i in range(len(coef)):
        if coef[i] != 0:
            aux = np.append(aux,coef[i])
        else:
            nnegativas = -1
    for i in range(len(aux)-1):
        if aux[i] * aux[i+1] < 0:
            npositivas+=1
        elif nnegativas != -1:
            nnegativas+=1
    return (npositivas,nnegativas)

Para a função $x^5-2x^4+x^3-2x^2+5$ e para $x^3-3x^2-6x+8$ ache o intervalo das raizes positivas e negativas, o número de raízes de cada tipo e plote um grafico para valores desde o limite inferior negativo até o limite superior positivo:

In [98]:
p0 = np.array([5,0,-2,1,-2,1])
p1 = np.array([8,-6,-3,1])

print(p0)
print(LimitesAlgebricos(p0))
print(nraizes(p0))

print(p1)
print(LimitesAlgebricos(p1))
print(nraizes(p1))

[ 5  0 -2  1 -2  1]
(3.0, 0.6125741132772068, -2.379729661461215, -0.6125741132772068)
(4, -1)
[ 8 -6 -3  1]
(7.0, 0.5714285714285714, -3.8284271247461903, -0.6202041028867288)
(2, 1)


Faça um programa que receba uma equação transcendente (na forma de função) e um ponto e tente descobrir um intervalo com uma raiz (slide 80 de isolamento de raízes):

In [ ]:
def achaIntervalo(f,z): #Voce pode rodar a função aqui dentro chamando f(x)
    return (a,b) #intervalo

Teste seu método com a função abaixo:

In [ ]:
def func1(x):
    return np.sin(x)**2

achaIntervalo(func1,2.5)

Agora vamos implementar a bissecção. O método da bissecção recebe como parametro uma função e um intervalo, e encontra uma raiz neste intervalo usando uma busca binária. O método pode ter três critérios de parada:

- Número de Iterações
- Proximidade da raiz
- Proximidade entre iterações.

Aqui vamos implementar **os três**

In [ ]:
def bisseccao(f,a,b, niter=1000,minimo = 0.000001, proximidadeIter = 0.000001):
    
    return raiz

Agora vamos testar nosso método da bissecção com a função $e^x-x-2$ para o intervalo [-30,-1]: